#!/bin/bash
# Fusion Linux post installation script borrowed from CrunchBang Linux

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# Create flag
if [ ! -d "/home/$USER/.config/fusion-linux" ]; then
    mkdir -p /home/$USER/.config/fusion-creator
fi
if [ ! -f "/home/$USER/.config/fusion-linux/fusion-creator" ]; then
    touch /home/$USER/.config/fusion-linux/fusion-creator
    echo "X-GNOME-Autostart-enabled=false" >> ~/.config/autostart/fusion-creator.desktop
fi

# Vars
# LIBDIR="/usr/share/fusion-linux/fusion-creator/fusion-creator-libs"
LIBDIR="./fusion-creator-libs"
STEP="0"
STEPS=`ls -1 $LIBDIR | wc -l`
#Internet connection not counted as step, so -1
STEPS=$((STEPS-1))


# Run through steps
STEP=$((STEP+1))
. $LIBDIR/intro

. $LIBDIR/check-internet-connection

STEP=$((STEP+1))
. $LIBDIR/yum-update

#STEP=$((STEP+1))
#. $LIBDIR/fedora-utils

STEP=$((STEP+1))
. $LIBDIR/fusion-linux-essentials

STEP=$((STEP+1))
. $LIBDIR/install-skype

STEP=$((STEP+1))
. $LIBDIR/install-google-earth

STEP=$((STEP+1))
. $LIBDIR/sudo

STEP=$((STEP+1))
. $LIBDIR/redshift

STEP=$((STEP+1))
. $LIBDIR/dropbox

STEP=$((STEP+1))
. $LIBDIR/wallpaper

#STEP=$((STEP+1))
#. $LIBDIR/add-user-to-fuse-group

#STEP=$((STEP+1))
#. $LIBDIR/install-multisession

#STEP=$((STEP+1))
#. $LIBDIR/devel

if [ "$DEVEL" != true ]; then
    . $LIBDIR/fini
    exit 0
fi

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-version-control-tools

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-ssh-server

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-lamp-stack

#STEP=$((STEP+1))
#. $LIBDIR/devel-install-packaging-tools

. $LIBDIR/fini
exit 0
