#!/bin/bash

# Firstrun checks
if [ -d /home/liveuser ]; then
    exit 0    
fi

if [ -e "$HOME/.config/fusion-firstrun" ]; then
    exit 0   
fi


# Create flag
if [ ! -f "$HOME/.config/fusion-firstrun" ]; then
    touch $HOME/.config/fusion-firstrun
fi
if [ ! -f "/home/$USER/.config/fusion-linux/fusion-welcome" ]; then
    touch /home/$USER/.config/fusion-linux/fusion-welcome
    echo "X-GNOME-Autostart-enabled=false" >> ~/.config/autostart/fusion-firstrun.desktop
fi
