#!/bin/bash
# Fusion Linux image creator script

# make sure your target partition has atleast 10GB of free space

# become root
echo "\nPlease enter your root password\n"
su - -c '

# edit this entry to specify your target directory
directory=/home/fusion-linux2

# let's check if target directory is present:
if [ -d $directory ]; then
	echo "Directory path to $directory not present, would you like to create it? (y/n): "
	read -n1 a
	a=`echo $a | tr '[A-Z]' '[a-z]'`
	if [ "$a" = "y" ]; then
		mkdir -p $directory
	else
		echo "\nWhen you change your mind restart the script.\n"
		exit
	fi

# let's check if target directory has enough free space: 
if [ 'df $directory |grep /dev| awk '{print $4 }'| awk 'sub(".$", "")'' -gt 10 ]; then
	echo "\nYour chosen target partition has over 10GB of free space, save to continue.\n"
	sleep 5
else
	echo "\nNot enough free space, make sure your target partition has over 10GB of free space."
	exit
fi

# first install packages
yum install livecd-tools spin-kickstarts qemu-kvm wget unzip -y

# switch to your target directory and create work directories
cd $directory
mkdir -p $directory/temp
mkdir -p $directory/yum-cache

# now grab latest Fusion Linux kickstart files
wget https://github.com/valentt/Fusion-Linux/zipball/master
unzip master

livecd-creator -v -t $directory/temp/ --cache=$directory/yum-cache/ -f Fusion-Linux-17.0 -c $directory/valentt-Fusion-Linux-*/kickstarts/fusion-17/fusion-linux-17.0.ks

'

# run your Fusin Linux iso image
# qemu-kvm -m 768 -cdrom Fusion-Linux-17.0.iso



# Making a 32-bit spin ISO on a 64-bit machine
# https://fedoraproject.org/wiki/How_to_create_and_use_a_Live_CD#Making_a_32-bit_spin_ISO_on_a_64-bit_machine

# If you have an x86_64 machine you're building on but you want a 32-bit happy iso image, add the following before your livecd-creator command:

# setarch i686 livecd-creator [...]

