#!/bin/bash
# Fusion Linux image creator script

# make sure your target partition has atleast 10GB of free space

# become root
echo -e "\nPlease enter your root password\n:"
su - -c '

# edit this entry to specify your target directory
directory=/home/fusion-linux2

# let's check if target directory is present:
if [ ! -d $directory ]; then
	echo -e "Directory path to $directory not present, would you like to create it? (y/n): "
	read -n1 a
	a=`echo $a | tr '[A-Z]' '[a-z]'`
	if [ "$a" = "y" ]; then
		mkdir -p $directory
	else
		echo -e "\nWhen you change your mind restart the script.\n"
		exit
	fi
fi

# let's check if target directory has enough free space: 
freespace=`df -h $directory |grep /dev| awk '{print $4 }'| awk 'sub(".$", "")'`
if [ "$freespace" -gt "100" ]; then
	echo -e "\nYour chosen target partition has over 10GB of free space, save to continue.\n"
	sleep 5
else
	echo -e "\nNot enough free space, make sure your target partition has over 10GB of free space."
	exit
fi

# first install packages
yum install livecd-tools spin-kickstarts qemu-kvm wget unzip -y

# switch to your target directory and create work directories
cd $directory
mkdir -p $directory/temp
mkdir -p $directory/yum-cache

# now grab latest Fusion Linux kickstart files
wget https://github.com/valentt/Fusion-Linux/zipball/master
unzip master

livecd-creator -v -t $directory/temp/ --cache=$directory/yum-cache/ -f Fusion-Linux-17.0 -c $directory/valentt-Fusion-Linux-*/kickstarts/fusion-17/fusion-linux-17.0.ks

'
