#!/bin/bash
# Fusion Linux image creator script

# make sure your target partition has atleast 10GB of free space

# edit this entry to specify your target directory
export directory=/home/fusion-linux
user=$(whoami)

if [ "$user" != "root" ]; then
  echo ""
  echo "You need to run this script with root privileges"
  echo ""
  exit
else

# become root
#echo -e "\nPlease enter your root password:"
#su - -c '# enter root password

echo -e "Let's check that target directory $directory is present."
if [ ! -d $directory ]; then
	echo -e "Directory path to $directory not present, would you like to create it? (y/n): "
	read -n1 a
	a=`echo $a | tr '[A-Z]' '[a-z]'`
	if [ "$a" = "y" ]; then
		mkdir -p $directory
		if [ ! -d $directory ]; then
			echo -e "\nDirectory could not be created, something is wrong. Exiting."
			exit
		fi
	else
		echo -e "\nWhen you change your mind restart the script.\n"
		exit
	fi
	echo -e "Target directory $directory is present, continuing."
	sleep 3
fi

# let's check if target directory has enough free space: 
freespace=`df -h $directory |grep /dev| awk '{print $4 }'| awk 'sub(".$", "")'`
minspace=9.7
enough=`echo $freespace $minspace | awk '{if ($1 > $2) print "yes"; else print "no"}'`

if [ "$enough" = yes ]; then
	echo -e "\nYour chosen target partition has $freespace GB of free space, it is safe to continue.\n"
	sleep 1
else
	echo -e "\nNot enough free space, you have $freespace GB free, but atleast $minspace GB is needed."
	exit
fi

# first install packages
yum install livecd-tools spin-kickstarts qemu-kvm wget unzip -y

# switch to your target directory and create work directories
cd $directory
mkdir -p $directory/temp
mkdir -p $directory/yum-cache

# now grab latest Fusion Linux kickstart files
if [ ! -f master ]; then
  wget https://github.com/valentt/Fusion-Linux/zipball/master
  unzip master
else
  echo ""
  echo -e "Fusion linux master file already downloaded, delete if you wish to update it."
  echo ""
fi

livecd-creator -v -t $directory/temp/ --cache=$directory/yum-cache/ -f Fusion-Linux-17.0 -c $directory/valentt-Fusion-Linux-*/kickstarts/fusion-17/fusion-linux-mini.ks
#'
fi